---
- hosts: localhost
  tasks:
  - file: path=version_report.txt state=absent
  - file: path=version_report.txt state=touch

- hosts: ios
  tasks:
  - ios_command:
      commands: show version
      provider: "{{cli}}"
    register: result

  - lineinfile: 
      dest:   version_report.txt 
      regexp: "{{inventory_hostname}}"
      line:   "{{inventory_hostname}}: IOS version mismatch"
    when: "not ('Version {{version}}' in result.stdout[0])"