---
- hosts: ios
  tasks:
  - ios_command:
      commands: show version
      provider: "{{cli}}"
    register: result
    
  - fail: msg="Wrong Cisco IOS version"
    when: "not ('Version {{version}}' in result.stdout[0])"