---
- hosts: ios
  tasks:
  - ios_command:
      commands: show arp
      provider: "{{cli}}"

- hosts: nxos
  tasks:
  - nxos_command:
      commands: show ip arp
      provider: "{{cli}}"

- hosts: junos
  tasks:
  - junos_command:
      commands: show arp
      provider: "{{netconf}}"