---
- hosts: nxos
  name:  configure VLANs
  tags:  VLAN
  tasks:
  - nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.id}}" 
      state:   "{{item.state | default('present') }}"
      admin_state: "{{ item.admin | default('up') }}"
      name:    "{{item.name}}"
    with_items: "{{vlans}}"
