---
- name: Copy and deploy configurations
  hosts: all
  tasks:
  - block:
    - stat: path={{config_dir}}/{{inventory_hostname}}.conf
      register: stat
    - assert:
        that: stat.stat.exists
        msg:  "Cannot find router configuration file for {{inventory_hostname}}"
    - name: Copy candidate configuration into routers
      local_action: >
        command /usr/bin/sshpass -p {{ansible_ssh_pass}}
        /usr/bin/scp {{config_dir}}/{{inventory_hostname}}.conf {{ansible_user}}@{{ansible_host|default(inventory_hostname)}}:flash:candidate.cfg
    tags: [ copy ]
  - block:
    - ios_command: commands="reload in 5" authorize=yes timeout=180
    - ios_command:
        commands:
          - replace flash:candidate.cfg force
        authorize: yes
        timeout: 180
      register: replace
      tags: [ print_action ]
    - ios_command: commands="reload cancel" authorize=yes

    - file: path={{build_dir}}/results state=directory
      check_mode: no
    - copy:
        content: |

          *********************************
          Results on {{inventory_hostname}}
          *********************************

          {{replace.stdout[0]}}
        dest: "{{build_dir}}/results/{{inventory_hostname}}.txt"
      delegate_to: localhost
    - assemble: src={{build_dir}}/results dest={{build_dir}}/results.txt
      run_once: true
    tags: [ deploy ]
