---
- name: Remove Loopback Networks on Each Switch
  hosts: switches
  connection: local
  tasks: 
    - name: Destroy Local Loopback Interfaces
      with_items: "{{ local_loopbacks }}"
      nxos_interface: 
        host: "{{ inventory_hostname }}"
        transport: nxapi 
        interface: "{{ item.name }}"
        state: absent
        mode: layer3
