---
- hosts: ios
  gather_facts: no
  tasks:
  - raw: "show arp"
    register: show
  - debug: var=show.stdout_lines

- hosts: nxos
  gather_facts: no
  tasks:
  - raw: "show ip arp"
    register: show
  - debug: var=show.stdout_lines
