---
- hosts: all
  gather_facts: no
  tasks:
  - raw: "show arp"
    register: show_ios
    when: "'ios' in group_names"
  - raw: "show ip arp"
    register: show_nxos
    when: "'nxos' in group_names"
  - debug: 
      var: |
        show_ios.stdout_lines|
          default(show_nxos.stdout_lines)
