---
ansible_device_os: ios
version: "15.5(4)M"
cli:
  username:  "{{ansible_user}}"
  password:  "{{ansible_password}}"
  host:      "{{inventory_hostname}}"
  transport: cli
ping_target: [ '172.16.1.1', '172.16.1.12', '172.16.1.100', '172.16.1.105' ]