---
- hosts: all
  gather_facts: no
  name: Create directory
  connection: local
  tasks:
  - file: path=configs state=absent
    run_once: true
  - file: path=configs state=directory
    run_once: true

- name: Build configurations
  hosts: all
  connection: local
  gather_facts: no
  tags: build
  tasks:
  - name: create configuration from platform-specific template
    template: src={{ansible_device_os}}/common.j2 dest=configs/{{inventory_hostname}}.txt