---
- hosts: all
  name: Create directory
  connection: local
  tasks:
  - file: path=configs state=directory

- hosts: ios
  connection: local
  tasks:
  - template: src=ios/common.j2 dest=configs/{{inventory_hostname}}.txt
    name: create configuration for IOS devices

- hosts: nxos
  connection: local
  tasks:
  - template: src=nxos/common.j2 dest=configs/{{inventory_hostname}}.txt
    name: create configuration for Nexus devices
