---
- hosts: all
  name: Create directory
  connection: local
  gather_facts: no
  tags: always
  tasks:
  - file: path=configs state=directory
    run_once: true

- name: Build configurations
  hosts: all
  connection: local
  gather_facts: no
  tags: build
  tasks:
  - name: create configuration from platform-specific template
    template: src={{ansible_device_os}}/common.j2 dest=configs/{{inventory_hostname}}.txt

- hosts: all
  name: Deploy configurations
  connection: local
  gather_facts: no
  tags: deploy
  tasks:
  - name: copy configuration into the device running config
    local_action: >
      command /usr/bin/sshpass -p {{ansible_ssh_pass}} 
      /usr/bin/scp configs/{{inventory_hostname}}.txt {{ansible_user}}@{{inventory_hostname}}:running-config
