---
- name: Retrieve BGP neighbor information
  hosts: all
  roles:
  - napalm
  tasks:
  - ios_command:
      commands: [ show ip ospf neighbor ]
    register: ospf_printout

  - include: ../../tools/include/snapshot.yml
    when: snapshot is defined

  - name: T1
    debug: msg={{ospf_printout.stdout}}

  - debug: msg={{ ospf_printout.stdout[0] | parse_cli_textfsm('textfsm/cisco_ios_show_ip_ospf_neighbor.template') }}