---
- name: Retrieve OSPF neighbor information
  hosts: all
  roles:
  - napalm
  tasks:
  - ios_command:
      commands: [ show ip ospf neighbor ]
    register: ospf_printout

  - debug: msg={{ospf_printout.stdout}}
  - debug: msg={{ ospf_printout.stdout[0] | parse_cli_textfsm('textfsm/cisco_ios_show_ip_ospf_neighbor.template') }}