---
- name: Retrieve OSPF neighbor information
  hosts: all
  roles:
  - napalm
  tasks:
  - ios_command:
      commands:
      - "{{ show_command | default('show ip ospf neighbor') }}"
    register: ospf_printout

  - debug: msg={{ ospf_printout.stdout[0] }}
  - set_fact: filter={{ filters + cli_filter|default('ios_ospf_neighbor.yml') }}
  - debug: msg={{ ospf_printout.stdout[0] | parse_cli(filter) }}