#! /usr/bin/env ansible-playbook
#
---
- hosts: all
  tasks:
  - block:
    - set_fact: results={{inventory_dir}}/results
    - file: path={{results}} state=directory
      run_once: true
    tags: [ always ]

  - name: Get device facts
    napalm_get_facts:
      hostname: "{{ansible_host|default(inventory_hostname)}}"
      username: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      dev_os: "{{ansible_os}}"
      optional_args:
        port: "{{api_port|default(ansible_port)|default(22)}}"
      filter:
      - facts
      - interfaces_ip
    tags: [ dump,create ]

  - name: Save structured data in YAML files
    copy:
      content: |
        {{hostvars[inventory_hostname]|to_nice_yaml(indent=4)}}
      dest: "{{results}}/{{inventory_hostname}}.yml"
    tags: [ dump ]

  - name: Create host file entries
    template: src=hosts.j2 dest={{results}}/hosts
    tags: [ create, install ]

  - name: Create zone file entries
    template: src=zone.j2 dest={{results}}/inaddr.arpa
    tags: [ create, install ]

  - blockinfile:
      path: /etc/hosts
      block: "{{ lookup('file', results ~ '/hosts') }}"
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    delegate_to: localhost
    run_once: true
    become: yes
    tags: [ install ]
