---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_vars: file=hosts.yml name=nodes
  - lineinfile: 
      dest:   /etc/hosts
      regexp: "{{item.key}}"
      line:   "{{item.value}} {{item.key}}"
    with_dict: "{{nodes}}"
    become: true
