#
# List of host names and IP addresses to be copied into /etc/hosts
#
# Edit this file based on your lab setup then run fixup.sh
#
# Remember: This is a YAML dictionary; you should know how to format it properly
#
---
r1.lab.local: "172.16.1.100"
s1.lab.local: "172.16.1.101"
