---
- include: "validate/input-file-format.yml"

- hosts: all
  name:  configure VLAN service
  tasks:
  - include_vars:
      file: "{{svcs|default(inventory_dir~'/services.yml')}}"
      name: "services"
    tags: [ always ]
  - include: tests/enable-debugging.yml

  - set_fact: data="{{lookup('template','templates/node-model.j2')}}"
    tags: [ always ]
  - local_action: >
      copy content="{{data|to_nice_json}}"
           dest="{{debug_output}}/{{inventory_hostname}}-model.json"
    when: debug_output is defined

  - include: "validate/predeploy-checks.yml"
    tags: [ predeploy ]

  - name: "Add/modify VLAN services"
    include: "provision/{{ansible_os}}-add.yml"
    tags: [ add, config ]

  - name: "Remove decommissioned VLAN services"
    include: "provision/{{ansible_os}}-remove.yml"
    tags: [ remove, config ]

  - name: "Reset interface facts"
    set_fact:
      vlan_list:       []
      vlan_interfaces: []

  - name: "Validate deployed VLAN services"
    include: "validate/deployed-services.yml"
    tags: [ validate ]

  - name: "Prepare for cleanup"
    include: "provision/cleanup-prepare.yml"
    tags: [ cleanup ]

  - name: "Execute cleanup"
    include: "provision/{{ansible_os}}-remove.yml"
    tags: [ cleanup ]
