---
- hosts: all
  tasks:
  - name: Get LLDP neighbors
    napalm_get_facts:
      hostname: "{{ansible_host|default(inventory_hostname)}}"
      username: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      dev_os: "{{ansible_os}}"
      optional_args:
        port: "{{api_port|default(ansible_port)|default(22)}}"
      filter:
      - facts
      - lldp_neighbors

  - name: Generate graph description file
    template: src={{template|default('graph.j2')}} dest=./{{output|default('network.dot')}}
    run_once: true
