#
# Get configuration from managed hosts using scp from system:running-config
#
---
- name:  Get device configuration
  hosts: all
  connection: local
  tasks:
  - name: Make sure we're in the right branch
    shell: git checkout {{branch|default('master')}}
    args:
      chdir: "{{repository}}"
    run_once: true
    changed_when: no

  - set_fact:
      scp_cmd: >
        sshpass -p {{ansible_ssh_pass}}
          scp {{ansible_user}}@{{ansible_host|default(inventory_hostname)}}:system:running-config
            {{repository}}/{{inventory_hostname}}.cfg

  - name: Grab configuration
    command: "{{scp_cmd}}"
