---
loopback: { ip: 10.0.1.3 }
LAN:
  interface: 'GigabitEthernet0/1'
  ip: 172.16.10.1
WAN:
  0:
    interface: 'GigabitEthernet0/2'
    ip: 10.0.7.22
    subnet: 255.255.0.0
#  1: { interface: 'FastEthernet1/0', ip: DHCP }
DMVPN: { 0: { ip: 192.168.0.3 }, 1: { ip: 192.168.1.3 } }
